#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-propro
Version  : 2.1.0
Release  : 3
URL      : https://pecl.php.net//get/propro-2.1.0.tgz
Source0  : https://pecl.php.net//get/propro-2.1.0.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: php-propro-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
# ext-propro
[![Build Status](https://travis-ci.org/m6w6/ext-propro.svg?branch=master)](https://travis-ci.org/m6w6/ext-propro)

%package dev
Summary: dev components for the php-propro package.
Group: Development
Requires: php-propro-lib = %{version}-%{release}
Provides: php-propro-devel = %{version}-%{release}
Requires: php-propro = %{version}-%{release}

%description dev
dev components for the php-propro package.


%package lib
Summary: lib components for the php-propro package.
Group: Libraries

%description lib
lib components for the php-propro package.


%prep
%setup -q -n propro-2.1.0
cd %{_builddir}/propro-2.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/php/ext/propro/php_propro.h
/usr/include/php/ext/propro/php_propro_api.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20190902/propro.so
